services:
  postgresql16:
    image: postgres:16
    container_name: postgresql16_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.10
    volumes:
      - ./db:/db

  php8:
    build:
      context: ./php8
      dockerfile: Dockerfile
    volumes:
      - ../src:/var/www/html
      - ./php8/conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.11

networks:
  mynetwork:
    external: true
    name: mynetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16